### ISSUE TITLE
Feature Request: Quick cite workflow

### ISSUE THREAD

**Issue by realCrush** [chrisgrieser/alfred-bibtex-citation-picker#12]
### Feature Requested

This is a great plugin for Alfred, thank you for your awesome work. 😇

I think it would be really helpful if we can make `search-add-cite` workflow more **fluently**: invoke Alfred, search some content in search bar on `arXiv` or `Google scholar` (this is for computer science, or user can **custom** sources), pick the article you want, and hit a enter key, boom, the bibtex of that article add to .bib file automatically (arXiv and Google scholar has open relative APIs), and you can then easily cite it with `+` in Alfred.

What I want to say is the **data collect** function of this plugin is a little weak, and it is very important for me to add bibtex and cite it to rush a paper, this process is time-consuming and painful for now, so I really want this plugin can solve it. 😊

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
> This is a great plugin for Alfred, thank you for your awesome work. 😇
Thanks 🙏 

> What I want to say is the data collect function of this plugin is a little weak

well, this tool is a citation picker after all 🤣 

What you are describing goes more into references adder like the Zotero Connector, which isn't really the goal of the project. It also would require a completely different code base to accomplish that, so I don't think I'm gonna implement this.

But since are doing Computer Science, you could probably build such a tool yourself? 😛
