### ISSUE TITLE
Feature Request: Allow search by author's first name / full name

### ISSUE THREAD

**Issue by kenanmike** [chrisgrieser/alfred-bibtex-citation-picker#16]
### Feature Requested

Can you configure search to include first name? So if I know the author I'm thinking of has a first name of Stephen but I don't remember their book or surname, I can search Stephen and it will show up.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Sorry, I think this might be a bit too niche of a Feature Request, since in academia it's mostly the other way round (we only know the last name but not the first name). For the few authors you know by first name but not last name, this would add a lot of noise since *every* entry will also match first name. 

If there are other people who also actually remember authors by first name instead of last name, I'll reconsider.
