### ISSUE TITLE
Feature Request: Add entries mirrored to a second BibTeX file

### ISSUE THREAD

**Issue by iandol** [chrisgrieser/alfred-bibtex-citation-picker#3]
### Feature Requested

For those of us using Bookends or Zotero, because both of these reference managers offer a one-way-sync only, edits made to the BibTeX file will be lost. While I personally use my own Bookends tools to quick-add refs directly to Bookends, I can see that being able to "Add entries" even if bookends wasn't running may be useful. I'm sure I'm not the only one.

If there was an option to specify an optional "mirror" BibTeX file, then any refs added to the main database would be mirrored to another BibTeX file and these could be imported by Bookends or Zotero manually.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Hi, sorry for the late response.

I am not sure whether your suggestion would actually be desirable. If you already use a ref manager like bookends, importing to bookends directly should always be preferable, since going the `Alfred workflow → bibtex → ref manager import` will add the potential for inconsistencies (e.g. your ref manager not importing the bibtex format correctly.)

I do not think the advantage of being able to add entries without Bookends being open is worth the decrease in consistency. Also it seems to be a rather niche requirement, since most users of ref managers would just use their existing importing tools instead of using a new one?

**Comment by chrisgrieser** [comment]
FYI, release 11.10 added the ability to add an optional, secondary bibtex library file. Not exactly what you asked about earlier, but in part I think?

https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/download/11.10.0/alfred-bibtex-citation-picker.alfredworkflow

**Comment by iandol** [comment]
Dear Chris, so if we add a reference, does it get added to both bib files? If so, then I think that your change does solve my original request. Let's say we have bib1 and bib2... bib1 is managed by Bookends/Jabref/Zotero, they write to that but don't read (well Jabref does I think). bib2 is small and not synced from Bookends/Zotero. Add a citation adds to bib1 and bib2, the bib1 changes are not seen by Bookends/Zotero. The user maually or automatically syncs from bib2 to their main database, and changes will get written out to bib1. Not ideal but should work?

**Comment by chrisgrieser** [comment]
New entries get added to bib1. So I think you should get what you want by switching bib1 and bib2?

**Comment by iandol** [comment]
Hi Chris, OK then I think that would solve this usecase 👍🏾
