### ISSUE TITLE
Feature Request: enhancement of tag searching

### ISSUE THREAD

**Issue by Elodie-0117** [chrisgrieser/alfred-bibtex-citation-picker#30]
### Feature Requested

I am not sure whether the tags searching (using #) include tag where the name contains space, cause when I type for example "#Firm value", results are strange, which has nothing to do with the correct articles that contain the "Firm value" tag.

Besides, as annotation tags are frequently used in Zotero, would it be possible to search for articles where the tag is attached in the annotation of the PDF?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Hi!

> I am not sure whether the tags searching (using #) include tag where the name contains space, cause when I type for example "#Firm value", results are strange, which has nothing to do with the correct articles that contain the "Firm value" tag.

Unfortunately, Alfred does not allow for searching in that manner; space will always serve as separator for search terms. So by typing `#Firm value` you search for articles with the tag `#Firm` and the term `value`. This is an restriction on Alfred's side, there is unfortunately nothing I can do about it. What I personally do is using dashes instead of spaces in all my tags: `#Firm-value`. This in turn should work fine with the workflow.

> Besides, as annotation tags are frequently used in Zotero, would it be possible to search for articles where the tag is attached in the annotation of the PDF?

No, unfortunately that also will not work, since this workflow literally does not read any data from Zotero itself, but only reads the data stored in the `.bib` file. You *could* maybe look into whether there is a Zotero tool that converts annotations tags into tags, which are then included in the exported `.bib` file. (But since I am not using Zotero myself, I can't give you any recommendations in this regard, sorry)

**Comment by Elodie-0117** [comment]
> 

Thanks very much. That’s clear and very helpful. Yes, i think i will rename all tags to remove the space. I see, i’ll probably consider to see whether i can transfer all annotation tags to tags. Thank you.
