### ISSUE TITLE
Is there a way to search for standalone note in Zotero

### ISSUE THREAD

**Issue by Elodie-0117** [chrisgrieser/alfred-bibtex-citation-picker#32]
### Feature Requested

i have a list of standalone notes which i need to frequently access to them while reading literature, but i found i cannot search for these notes using the bibtex-citation-picker?

honestly, this bibtex-citation-picker has dramatically changed my way of constantly navigating among articles, which i loved so much and have been so addicted to this to searching within my zotero database.

so if notes serarching is also supported of this tool, it would further advances my efficiency of literature reading and notes taking.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Hi! thanks for kind words! 😊

So, this workflow does not actually interact with Zotero itself, but only with the bibtex file exported by the Zotero Betterbibtex plugin. And to my knowledge (I don't use Zotero anymore), that plugin does not export your zotero standalone notes, so I am afraid there is no way this workflow will be able to interact with standalone notes.

The only note-related feature this plugin has is to create/open [literature notes in form of markdown notes](https://github.com/chrisgrieser/alfred-bibtex-citation-picker#literature-note-actions). I am not inclined to add more note-related features, since for proper note-management, most people tend to use a dedicated note-taking app like [Obsidian](https://obsidian.md/), which are better suited for than the rather limited feature set of Zotero's notes.

In case that's something you consider, there are a lot of Zotero-using academics active in the Obsidian community (e.g. the `#academia` channel in Obsidian's discord server), and you will actually be able to search your notes via Alfred as well, since I coincidentally also created [a quite extensive Alfred workflow for Obsidian](https://alfred.app/workflows/chrisgrieser/shimmering-obsidian/) 😅

**Comment by Elodie-0117** [comment]
> Hi! thanks for kind words! 😊
> 
> So, this workflow does not actually interact with Zotero itself, but only with the bibtex file exported by the Zotero Betterbibtex plugin. And to my knowledge (I don't use Zotero anymore), that plugin does not export your zotero standalone notes, so I am afraid there is no way this workflow will be able to interact with standalone notes.
> 
> The only note-related feature this plugin has is to create/open [literature notes in form of markdown notes](https://github.com/chrisgrieser/alfred-bibtex-citation-picker#literature-note-actions). I am not inclined to add more note-related features, since for proper note-management, most people tend to use a dedicated note-taking app like [Obsidian](https://obsidian.md/), which is better suited for note-taking than the rather limited feature set of Zotero's notes.
> 
> In case that's something you want to consider, there are a lot of Zotero-using academics active in the Obsidian community (e.g. the `#academia` channel in Obsidian's discord server), and you will actually be able to search your notes via Alfred as well, since I coincidentally also created [a quite extensive Alfred workflow for Obsidian](https://alfred.app/workflows/chrisgrieser/shimmering-obsidian/) 😅

Thanks for the thorough illustration, i see and can resonate your point. I will consider better way to make notes in zotero (may also have a try of the markdown notes if i still prefer to access these notes more efficiently using this plugin), anyway, thank you!
