### ISSUE TITLE
[Bug]: Workflow not working

### ISSUE THREAD

**Issue by axbax** [chrisgrieser/alfred-bibtex-citation-picker#47]
### Bug Description

After updates to Zotero 7 beta the workflow is not working. It doesn't load references. There was an issue with Better BibTex, but it appears to have been updated now. Still, the citation picker doesn't work. Is there something you can do to fix this, or is it caused by Zotero/Better BibTex? Thanks!

### Debugging Log

```Text
N/A
```

### Sample BibTeX Entries

```BibTeX
N/A
```

### Buffer Files

N/A

### Workflow Configuration

N/A

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-bibtex-citation-picker/releases/latest) of this workflow.
- [X] I have tried manually reloading the buffer (Alfred keyword `scp`, select `Force Buffer Reload`).

**Comment by chrisgrieser** [comment]
Hi, unfortunately, there is nothing I can do since you skipped all the form fields. 
- I cannot tell if a specific error is causing this, since you did not share a debugging log
- I cannot tell if a specific configuration causes the issue, since you did nor share your workflow config.
- I cannot tell if the Zotero 7 beta maybe formats the BibTeX entries in a new way, since you did not provide any sample entries.
- ...

This bug report is a bit like the equivalent of going to the doctor, telling them "I have pain, please fix it", and expecting to get help without mentioning which part of the body hurts.

Please create a new bug report without skipping the required form fields.

**Comment by axbax** [comment]
I'm sorry! I will create a new report with relevant information.
